server:
  port: 8026
  servlet:
    session:
      timeout: 600
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/smscode
    username: root
    password: 123456789
    hikari:
      maximum-pool-size: 100     # 峰值并发连接
      minimum-idle: 5            # 平时保持
      connection-timeout: 2000   # 2 秒就能发现拿不到连接，而不是 30 s
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  threads:
    virtual:
      enabled: true

#  data:
#    redis:
#      # Redis?????????0?
#      database: 4
#      # Redis?????
#      host: 127.0.0.1
#      # Redis???????
#      port: 6379
#      # Redis?????????????
#      # password:
#      # ??????
#      timeout: 10s
#      lettuce:
#        pool:
#          # ????????
#          max-active: 200
#          # ???????????????????????
#          max-wait: -1ms
#          # ???????????
#          max-idle: 10
#          # ???????????
#          min-idle: 0


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

#
sa-token:
  # token?? (????cookie??)
  token-name: Account-token
  # token??????s ??30?, -1??????
  timeout: 2592000
  # token????? (???????????token??) ??: ?
  active-timeout: -1
  # ???????????? (?true???????, ?false?????????)
  is-concurrent: true
  # ?????????????????token (?true?????????token, ?false?????????token)
  is-share: false
  # token??
  token-style: simple-uuid
  # ????????
  is-log: true
  # ???????????token
  is-read-body: true
  # ?????header???token
  is-read-header: true
  # ?????cookie???token
  is-read-cookie: true
  # ????????
  #is-cross: true
  #jwt??/Base64 ??
#  jwt-secret-key: 6LWE5rqQ5bqT57O757uf
  # token??
  #token-prefix: Bearer


admin:
  username: admin
  password: admin
  debug: true
